version: '3.5'

services:
  mda:
    ports:
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"
      - "0.0.0.0:587:587"

  mta:
    ports:
      - "0.0.0.0:25:25"

  web:
    ports:
      - "0.0.0.0:9091:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.entrypoints=http"
      - "traefik.http.routers.mail.rule=Host(`mail.thievent.org`)"
      - "traefik.http.middlewares.mail-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mail.middlewares=mail-https-redirect"
      - "traefik.http.routers.mail-secure.entrypoints=https"
      - "traefik.http.routers.mail-secure.rule=Host(`mail.thievent.org`)"
      - "traefik.http.routers.mail-secure.tls=true"
      - "traefik.http.routers.mail-secure.tls.certresolver=http"
      - "traefik.http.routers.mail-secure.service=mail"
      - "traefik.http.services.mail.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-proxy"
