version: '2'

services:
  db:
    image: jeboehm/mailserver-db:latest
    build: ./db
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql

  mta:
    image: jeboehm/mailserver-mta:latest
    build: ./mta
    restart: on-failure:5
    env_file: .env
    tmpfs:
      - /var/log
    links:
      - db
      - mda

  mda:
    image: jeboehm/mailserver-mda:latest
    build: ./mda
    restart: on-failure:5
    env_file: .env
    tmpfs:
      - /etc/dovecot
    volumes:
      - data-mail:/var/vmail
    links:
      - db

volumes:
  data-db:
    driver: local

  data-mail:
    driver: local
