version: '2'

services:
  db:
    image: jeboehm/mailserver-db:latest
    build: ./db
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"

  mta:
    image: jeboehm/mailserver-mta:latest
    build: ./mta
    restart: on-failure:5
    env_file: .env
    tmpfs:
      - /var/log
    links:
      - db
      - mda
    ports:
      - "127.0.0.1:25:25"

  mda:
    image: jeboehm/mailserver-mda:latest
    build: ./mda
    restart: on-failure:5
    env_file: .env
    tmpfs:
      - /etc/dovecot
    volumes:
      - data-mail:/var/vmail
    links:
      - db
    ports:
      - "127.0.0.1:110:110"
      - "127.0.0.1:143:143"

volumes:
  data-db:
    driver: local

  data-mail:
    driver: local
